# Kafka configuration
kafka:
  bootstrap_servers: "kafka.smo.svc.cluster.local" # Kafka host
  port: 9092 # Kafka port number
  enable_auto_commit: True
  auto_commit_interval_ms: 6000
  auto_offset_reset: "earliest"
  group_id: "influxdb-connector"
  client_id: "influxdb-connector"
  poll_timeout_seconds: 1
  topics:
  - heartbeat
  - measurementsforvfscaling



# Influx DB configuration
influxdb:
  host: "influxdb.smo.svc.cluster.local"
  port: 8086
  database: "smo"




# Logging configuration
logging:
  level: DEBUG # Logging level